### ISSUE TITLE
tprofile.log数据异常

### ISSUE THREAD

**Issue by lileichinasoft** [alibaba/TProfiler#35]
-rw-r--r-- 1 root root       0 Apr 22 17:27 ../dist/tmethod.log
-rw-r--r-- 1 root root     287 Apr 22 17:38 ../dist/tprofiler.log
-rw-r--r-- 1 root root 2660414 Apr 22 17:38 ../dist/tsampler.log

tprofiler.log里的数据，会多出很多的等号；应该是方法没执行导致的，可否过滤一下，没执行就不要输出等号了；谢谢！

线程ID 线程栈深度 方法ID 方法执行时间
》23      0       149     1464000
》=
》=
》=

**Comment by simplelzl** [comment]
这是因为profile.properties中includePackageStartsWith配置错误，导致transform未执行
