### ISSUE TITLE
能支持jdk1.7 吗？

### ISSUE THREAD

**Issue by snaigle** [alibaba/TProfiler#39]
我们的项目使用jdk1.7编译和运行，是否可以使用#tprofile

**Comment by solio** [comment]
ReadMe上写的是require JDK1.6
但是我们项目用的是JDK1.8也可以

**Comment by feiyan35488** [comment]
@solio  我先上测试环境搞一下，这个项目最后一个提交是2年前的事。
貌似近两年阿里的好多项目都不怎么维护了，如#dubbo# ,#webx# 等

**Comment by solio** [comment]
可以我们自己维护 @feiyan35488

**Comment by xueyichen** [comment]
@solio  想问下jdk1.8 可以用吗？
依赖的asm需要更新成哪个版本呢？

**Comment by mccxj** [comment]
需要升级到asm5.x， 我已经修改了。

见 https://github.com/mccxj/TProfiler/commit/36e45e0563c56c8060ddd72ad2b8208169f3b4d3
